main: com.ankoki.skriptdiscord.SkriptDiscord
name: skript-discord
version: 1.0
author: Ankoki
website: 'https://www.github.com/Ankoki-Dev/skript-discord'
description: §7skript-discord §fis used to provide discord implementation to Skript.
api-version: 1.13
depend:
  - Skript